function(_grit_resolve_instantiation_template out_template_path out_template_dir out_output_stem template_arg)
    if(IS_ABSOLUTE "${template_arg}")
        set(template_path "${template_arg}")
    else()
        set(template_path "${CMAKE_CURRENT_SOURCE_DIR}/${template_arg}")
    endif()

    get_filename_component(template_name "${template_path}" NAME)
    if(template_name MATCHES "^(.*)\\.inst\\.cpp\\.in$")
        set(output_stem "${CMAKE_MATCH_1}")
    elseif(template_name MATCHES "^(.*)\\.cpp\\.in$")
        set(output_stem "${CMAKE_MATCH_1}")
    else()
        string(REGEX REPLACE "\\.in$" "" output_stem "${template_name}")
    endif()

    get_filename_component(template_dir "${template_path}" DIRECTORY)
    set(${out_template_path} "${template_path}" PARENT_SCOPE)
    set(${out_template_dir} "${template_dir}" PARENT_SCOPE)
    set(${out_output_stem} "${output_stem}" PARENT_SCOPE)
endfunction()

function(generate_scalar_instantiations out_var)
    set(options)
    set(oneValueArgs TEMPLATE OUTPUT_DIR)
    set(multiValueArgs SCALARS)
    cmake_parse_arguments(PARSE_ARGV 1 GRIT_INST "${options}" "${oneValueArgs}" "${multiValueArgs}")

    if(NOT GRIT_INST_TEMPLATE)
        message(FATAL_ERROR "generate_scalar_instantiations requires TEMPLATE")
    endif()

    _grit_resolve_instantiation_template(template_path template_dir output_stem "${GRIT_INST_TEMPLATE}")

    if(GRIT_INST_SCALARS)
        set(grit_inst_scalars ${GRIT_INST_SCALARS})
    else()
        set(grit_inst_scalars ${GRIT_ENABLED_SCALARS})
    endif()

    if(GRIT_INST_OUTPUT_DIR)
        set(output_dir "${GRIT_INST_OUTPUT_DIR}")
    else()
        set(output_dir "${CMAKE_CURRENT_BINARY_DIR}/generated/instantiations")
    endif()

    file(MAKE_DIRECTORY "${output_dir}")

    set(generated_sources)
    foreach(grit_scalar IN LISTS grit_inst_scalars)
        set(SCALAR "${grit_scalar}")
        if(grit_scalar MATCHES "^cx")
            set(SCALAR_IS_COMPLEX 1)
        else()
            set(SCALAR_IS_COMPLEX 0)
        endif()
        set(output_path "${output_dir}/${output_stem}.${grit_scalar}.cpp")
        configure_file("${template_path}" "${output_path}" @ONLY)
        set_property(SOURCE "${output_path}" APPEND PROPERTY INCLUDE_DIRECTORIES "${template_dir}")
        list(APPEND generated_sources "${output_path}")
    endforeach()

    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${template_path}")
    set(${out_var} "${generated_sources}" PARENT_SCOPE)
endfunction()

