cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED GRIT_DEPS_BUILD_DIR)
    set(GRIT_DEPS_BUILD_DIR ${CMAKE_BINARY_DIR}/pkg-build)
endif()

if(NOT DEFINED GRIT_DEPS_INSTALL_DIR)
    set(GRIT_DEPS_INSTALL_DIR ${CMAKE_INSTALL_PREFIX})
endif()

list(PREPEND CMAKE_PREFIX_PATH ${GRIT_DEPS_INSTALL_DIR})
list(REMOVE_DUPLICATES CMAKE_PREFIX_PATH)
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} CACHE INTERNAL "Paths for find_package config lookup" FORCE)

