cmake_minimum_required(VERSION 3.24)

find_package(OpenMP REQUIRED COMPONENTS CXX)
target_link_libraries(grit-config INTERFACE OpenMP::OpenMP_CXX)
list(APPEND GRIT_PUBLIC_DEPENDENCIES OpenMP::OpenMP_CXX)

find_package(atomic MODULE BYPASS_PROVIDER)
if(TARGET atomic::atomic)
    target_link_libraries(grit-config INTERFACE atomic::atomic)
    list(APPEND GRIT_PUBLIC_DEPENDENCIES atomic::atomic)
    set(GRIT_HAS_ATOMIC TRUE)
endif()

find_package(Eigen3 5)
if(NOT Eigen3_FOUND)
    find_package(Eigen3 3.4 REQUIRED)
endif()
list(APPEND GRIT_PUBLIC_DEPENDENCIES Eigen3::Eigen)
target_link_libraries(grit-config INTERFACE Eigen3::Eigen)

if(TARGET Eigen3::Eigen)
    set_property(TARGET Eigen3::Eigen APPEND PROPERTY INTERFACE_COMPILE_OPTIONS $<$<CXX_COMPILER_ID:GNU>:-Wno-psabi>)
endif()

find_package(fmt CONFIG QUIET)
if(fmt_FOUND)
    list(APPEND GRIT_PUBLIC_DEPENDENCIES fmt::fmt)
    target_link_libraries(grit-config INTERFACE fmt::fmt)
else()
    find_package(fmt REQUIRED)
endif()

find_package(spdlog CONFIG QUIET)
if(spdlog_FOUND)
    list(APPEND GRIT_PUBLIC_DEPENDENCIES spdlog::spdlog)
    target_link_libraries(grit-config INTERFACE spdlog::spdlog)
else()
    find_package(spdlog REQUIRED)
endif()
